---
- name: Copy a new network configuration "interfaces" file into place, after passing validation with ifup
  ansible.builtin.copy:
    src: 'eth_cfg'
    dest: '/etc/network/interfaces.d/eth_cfg'
    validate: /usr/sbin/ifup --no-act -i %s eth1 eth2
  notify: Restart Networking

- name: Allow IPv4 forwarding
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward=1'
    state: present
  notify: Reload kernel config

- name: Install Dnsmasq
  ansible.builtin.apt:
    name: 'dnsmasq'
    update_cache: true

- name: Copy Dnsmasq configuration
  ansible.builtin.copy:
    src: 'dnsmasq.conf'
    dest: '/etc/dnsmasq.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Restart and enable Dnsmasq
  ansible.builtin.service:
    name: 'dnsmasq'
    enabled: true
    state: restarted
